quarkus:
  datasource:
    db-kind: oracle
    jdbc:
      url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  http:
    port: ${PORT:8080}
    cors:
      ~: true
      origins: "*"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
      headers: "*"
  log:
    level: OFF
    console:
      enable: false

# Table allowlist configuration
allowlist:
  tables:
    - schema: TRDMGMR
      table: AGENT_MGMT
      pk-columns:
        - AGENT_ID
    # - schema: HR
    #   table: DEPARTMENT
    #   pk-columns:
    #     - DEPT_ID
    # - schema: HR
    #   table: JOB_HISTORY
    #   pk-columns:
    #     - EMPLOYEE_ID
    #     - START_DATE
