quarkus:
  datasource:
    db-kind: oracle
    jdbc:
      url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  http:
    port: ${PORT:8080}
    cors:
      ~: true
      origins: "*"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
      headers: "*"
  log:
    level: INFO
    console:
      json: false
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{2.}] (%t) %s%e%n"
    category:
      "com.auditpatchx":
        level: DEBUG

# Table allowlist configuration
allowlist:
  tables:
    - schema: TRDMGMR
      table: AGENT_MGMT
      pk-columns:
        - AGENT_ID
    - schema: TRDMGMR
      table: TRANSACTIONS
      pk-columns:
        - TRANSACTION_ID
    # - schema: HR
    #   table: JOB_HISTORY
    #   pk-columns:
    #     - EMPLOYEE_ID
    #     - START_DATE
